spireOgelCacheJobCron: 0 0 0 * * ?

cacheTimeout: 1000

adminLogin: "${ADMIN_LOGIN}"
adminPassword: "${ADMIN_PASSWORD}"

serviceLogin: "${SERVICE_LOGIN}"
servicePassword: "${SERVICE_PASSWORD}"

jerseyClient:
  timeout: 10000ms

virtualEuOgelId: "${VIRTUAL_EU_OGEL_ID}"

spireClientUserName: "${SPIRE_CLIENT_USERNAME}"
spireClientPassword: "${SPIRE_CLIENT_PASSWORD}"
spireClientUrl: "${SPIRE_CLIENT_URL}"

server:
  type: default
  applicationConnectors:
    - type: http
      port: ${PORT}
  requestLog:
    appenders:
      - type: json-console-access

logging:
  level: INFO
  appenders:
    - type: json-console

database:
  driverClass: org.postgresql.Driver
  url: "${VCAP_JDBC_URL}"
  schema: "${DATABASE_SCHEMA}"
  properties:
    charSet: UTF-8
  maxWaitForConnection: 30s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: ${DB_POOL_MIN_SIZE}
  maxSize: ${DB_POOL_MAX_SIZE}
  initialSize: ${DB_POOL_MIN_SIZE}
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
