spireOgelCacheJobCron: 0 0 0 * * ?

cacheTimeout: 1000

adminLogin: "ENTER_USERNAME_HERE"
adminPassword: "ENTER_PASSWORD_HERE"

serviceLogin: "ENTER_USERNAME_HERE"
servicePassword: "ENTER_PASSWORD_HERE"

jerseyClient:
  timeout: 10000ms

virtualEuOgelId: "OGL61"

spireClientUserName: "ENTER_USERNAME_HERE"
spireClientPassword: "ENTER_PASSWORD_HERE"
spireClientUrl: "https://lite-service-mocking-dev.cloudapps.digital/spire/fox/ispire/"

server:
  type: default
  applicationConnectors:
    - type: http
      port: 8080
  requestLog:
    appenders:
      - type: json-console-access

logging:
  level: INFO
  appenders:
      - type: console
        includeCallerData : true
        logFormat: "[%mdc{corrID}] %d [%p] %marker %logger %m%n"

database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/postgres?currentSchema=ogelsvc
  user: postgres
  password: password
  properties:
    charSet: UTF-8
  maxWaitForConnection: 30s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute


