INSERT INTO LOCAL_OGEL (ID, NAME, CANLIST, CANTLIST, MUSTLIST, HOWTOUSELIST)
VALUES ('OGLX', 'NameOGLX', 'null', 'null', 'null', 'null');
INSERT INTO LOCAL_OGEL (ID, NAME, CANLIST, CANTLIST, MUSTLIST, HOWTOUSELIST)
VALUES ('OGLY', 'NameOGLY', 'null', 'null', 'null', 'null');
INSERT INTO LOCAL_OGEL (ID, NAME, CANLIST, CANTLIST, MUSTLIST, HOWTOUSELIST)
VALUES ('OGLZ', 'NameOGLZ', 'null', 'null', 'null', 'null');