INSERT INTO LOCAL_OGEL (ID, NAME, CANLIST, CANTLIST, MUSTLIST, HOWTOUSELIST)
VALUES ('OGLX', 'NameOGLX', '["CanList for OGLX"]', '["CantList for OGLX"]', null, null);
INSERT INTO LOCAL_OGEL (ID, NAME, CANLIST, CANTLIST, MUSTLIST, HOWTOUSELIST)
VALUES ('OGLY', 'NameOGLY', '["CanList for OGLY"]', '["CantList for OGLY"]', null, null);
INSERT INTO LOCAL_OGEL (ID, NAME, CANLIST, CANTLIST, MUSTLIST, HOWTOUSELIST)
VALUES ('OGLZ', 'NameOGLZ', '["CanList for OGLZ"]', '["CantList for OGLZ"]', null, null);
