INSERT INTO LOCAL_CONTROL_CODE_CONDITIONS (OGEL_ID, CONTROL_CODE, CONDITION_DESC, CONDITION_DESC_CONTROL_CODES, ALLOWED)
VALUES ('OGLX', '11', 'ConditionDesc for OGLX', null, 'true');
INSERT INTO LOCAL_CONTROL_CODE_CONDITIONS (OGEL_ID, CONTROL_CODE, CONDITION_DESC, CONDITION_DESC_CONTROL_CODES, ALLOWED)
VALUES ('OGLY', '22', 'ConditionDesc for OGLY', null, 'true');
INSERT INTO LOCAL_CONTROL_CODE_CONDITIONS (OGEL_ID, CONTROL_CODE, CONDITION_DESC, CONDITION_DESC_CONTROL_CODES, ALLOWED)
VALUES ('OGLZ', '33', 'ConditionDesc for OGLZ', '["33"]', 'true');